server:
  port: 8086

spring:
  application:
    name: EDULEARN-PROGRESS-SERVICE

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:mysql://localhost:3306/edulearn_progress?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: edulearn
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    com.edulearn.progress: INFO
