server:
  port: 8081
  forward-headers-strategy: framework

spring:
  application:
    name: EDULEARN-AUTH-SERVICE

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  datasource:
    url: jdbc:mysql://localhost:3306/edulearn_auth?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: edulearn
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      expiration: 86400000

  oauth2:
    redirect-uri: https://edulearnweb.duckdns.org/auth/google/callback

  reset-password:
    frontend-url: https://edulearnweb.duckdns.org/auth/reset-password

app:
  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
    full-name: ${ADMIN_FULL_NAME}

logging:
  level:
    root: INFO
    com.edulearn.auth: INFO
