server:
  port: 8085

spring:
  application:
    name: EDULEARN-ASSESSMENT-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/edulearn_assessments?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: edulearn
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
    com.edulearn.assessment: INFO
